// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF-EBGIJmtdV8mfuK7WCvgxZV815h9GLk',
    appId: '1:110344351687:web:95f532c63fbd33b44a33e2',
    messagingSenderId: '110344351687',
    projectId: 'currents-api',
    authDomain: 'currents-api.firebaseapp.com',
    storageBucket: 'currents-api.appspot.com',
    measurementId: 'G-KPHNZ6JGZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu5adesGnTsz8-0drlcCjmjjQAqD4uCOU',
    appId: '1:110344351687:android:41be48bf2f90947c4a33e2',
    messagingSenderId: '110344351687',
    projectId: 'currents-api',
    storageBucket: 'currents-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsmmu9Jwd8yu20gCaEqBZx8VJ44oQ0AjM',
    appId: '1:110344351687:ios:2511061cd94b85fd4a33e2',
    messagingSenderId: '110344351687',
    projectId: 'currents-api',
    storageBucket: 'currents-api.appspot.com',
    androidClientId: '110344351687-2h9pkfogoiochb484lf1lqarrbt3ej4g.apps.googleusercontent.com',
    iosClientId: '110344351687-dl0reto5nbq2ekbupnes1bcbtpavgnvo.apps.googleusercontent.com',
    iosBundleId: 'com.tikalk.currentsapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsmmu9Jwd8yu20gCaEqBZx8VJ44oQ0AjM',
    appId: '1:110344351687:ios:a2e747a7f737482e4a33e2',
    messagingSenderId: '110344351687',
    projectId: 'currents-api',
    storageBucket: 'currents-api.appspot.com',
    androidClientId: '110344351687-2h9pkfogoiochb484lf1lqarrbt3ej4g.apps.googleusercontent.com',
    iosClientId: '110344351687-cud7rqaueq3cdtpvhn2i4rrssslrv27s.apps.googleusercontent.com',
    iosBundleId: 'com.tikalk.currentsapi.RunnerTests',
  );
}
